---
bazarr_enabled: false
bazarr_available_externally: 'false'

# directories
bazarr_data_directory: '{{ docker_home }}/bazarr'
bazarr_tv_directory: '{{ tv_root }}'
bazarr_movies_directory: '{{ movies_root }}'

# uid/gid
bazarr_user_id: '{{ user_id }}'
bazarr_group_id: '{{ group_id }}'

# network
bazarr_port: '6767'
bazarr_hostname: 'bazarr'
