---
- name: Watchtower Docker Container
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    pull: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    env:
      TZ: '{{ timezone }}'
    command: '{{ watchtower_command }}'
    restart_policy: unless-stopped
