- name: apt install nfs tools
  apt:
    name: nfs-common

- name: Mount an NFS volume
  ansible.posix.mount:
    src: 192.168.1.162:/mnt/zfs/public
    path: "{{ samba_shares_root }}"
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
  when: (nfs_enabled | default(False)) 
