---
packages:
  - git
  - neovim
  - tmux
  - btop

hostname: nasa
timezone: Europe/Paris

# services
portainer_enabled: true
traefik_enabled: true
#filebrowser_enabled: true
uptime_kuma_enabled: true
watchtower_enabled: true

minecraft_available_externally: 'true'
plex_available_externally: 'true'
uptime_kuma_available_externally: 'true'
librespeed_available_externally: 'true'
portainer_available_externally: 'true'
jellyfin_available_externally: 'true'
filebrowser_available_externally: 'true'
nextcloud_available_externally: 'true'
bitwarden_available_externally: 'true'

root_directory: /srv

personal_user: luffy
personal_group: luffy
personal_directory: '{{ root_directory}}/cyril'
personal_user_id: '1000'
personal_group_id: '1000'

user: luffy
ansible_user: luffy
security_sudoers_passwordless: 
  - luffy
group: luffy
email: ghlcyril@gmail.com
domain: cghali.fr
user_id: '1000'
group_id: '1000'
ansible_python_interpreter: /usr/bin/python3

samba_shares_root: '{{ root_directory}}/public'

downloads_root: '{{ samba_shares_root }}/downloads'
documents_root: '{{ samba_shares_root }}/documents'
movies_root: '{{ samba_shares_root }}/movies'
anime_root: '{{ samba_shares_root }}/anime'
tv_root: '{{ samba_shares_root }}/tv'
music_root: '{{ samba_shares_root }}/music'
videos_root: '{{ samba_shares_root }}/videos'
coptic_root: '{{ samba_shares_root }}/coptic'
podcasts_root: '{{ samba_shares_root }}/podcasts'
books_root: '{{ samba_shares_root }}/books'
audiobooks_root: '{{ samba_shares_root }}/audiobooks'
comics_root: '{{ samba_shares_root }}/comics'
photos_root: '{{ samba_shares_root }}/photos'
samba_server_string: SMB Server
samba_shares:
  - name: downloads
    comment: 'Stuff downloaded'
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: '{{ downloads_root }}'

  - name: documents
    comment: 'Documents'
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: '{{ documents_root }}'

  - name: movies
    comment: 'Movies'
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: '{{ movies_root }}'

  - name: tv
    comment: 'TV Episodes'
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: '{{ tv_root }}'

  - name: anime
    comment: 'Anime Episodes'
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: '{{ anime_root }}'

  - name: music
    comment: 'Music'
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: '{{ music_root }}'

  - name: podcasts
    comment: 'Podcasts'
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: '{{ podcasts_root }}'

  - name: dump
    comment: 'File dump'
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: '{{  samba_shares_root  }}/dump'

  - name: games
    comment: 'Games'
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: '{{ samba_shares_root }}/games'

  - name: photos
    comment: 'Pictures'
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: '{{ photos_root }}'

  - name: books
    comment: 'Books'
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: '{{ books_root }}'

  - name: audiobooks
    comment: 'Audiobooks'
    guest_ok: yes
    public: yes
    writable: yes
    browsable: yes
    path: '{{ samba_shares_root }}/audiobooks'

  - name: comics
    comment: 'Comics'
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: '{{ comics_root }}'

  # - name: coptic
  #   comment: 'Coptic'
  #   guest_ok: yes
  #   public: yes
  #   writable: yes
  #   browseable: yes
  #   path: '{{ coptic_root }}'

# Seems to break browsing of the \\server-name shares root when enabled
samba_mitigate_cve_2017_7494: false
samba_apple_extensions: yes
samba_guest_account: nasa
samba_map_to_guest: Bad Password

# The NetBIOS hostname used by Samba on your network
samba_netbios_name: '{{ hostname }}'

openvpn_provider: 'NORDVPN'
