---
- name: Create uptime_kuma Directories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ uptime_kuma_config_directory }}'

- name: uptime_kuma Docker Container
  docker_container:
    name: uptime_kuma
    image: louislam/uptime-kuma:1
    pull: true
    env:
      TZ: '{{ timezone }}'
      PUID: '{{ uptime_kuma_user_id }}'
      PGID: '{{ uptime_kuma_group_id }}'
    volumes:
      - '{{ uptime_kuma_config_directory }}:/app/data:rw'
    ports:
      - '{{ uptime_kuma_port_http }}:3001'
    restart_policy: unless-stopped
    labels:
      traefik.enable: '{{ uptime_kuma_available_externally }}'
      traefik.http.routers.uptime_kuma.rule: 'Host(`{{ uptime_kuma_hostname }}.{{ domain }}`)'
      traefik.http.routers.uptime_kuma.tls.certresolver: 'letsencrypt'
      traefik.http.routers.uptime_kuma.tls.domains[0].main: '{{ domain }}'
      traefik.http.routers.uptime_kuma.tls.domains[0].sans: '*.{{ domain }}'
      traefik.http.services.uptime_kuma.loadbalancer.server.port: '3001'
